// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package com.danny.domain.proto;

public final class FruitProto {
  private FruitProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FruitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Fruit)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string category = 1;</code>
     */
    boolean hasCategory();
    /**
     * <code>required string category = 1;</code>
     */
    java.lang.String getCategory();
    /**
     * <code>required string category = 1;</code>
     */
    com.google.protobuf.ByteString
        getCategoryBytes();

    /**
     * <code>repeated .Apple apple = 2;</code>
     */
    java.util.List<com.danny.domain.proto.FruitProto.Apple> 
        getAppleList();
    /**
     * <code>repeated .Apple apple = 2;</code>
     */
    com.danny.domain.proto.FruitProto.Apple getApple(int index);
    /**
     * <code>repeated .Apple apple = 2;</code>
     */
    int getAppleCount();
    /**
     * <code>repeated .Apple apple = 2;</code>
     */
    java.util.List<? extends com.danny.domain.proto.FruitProto.AppleOrBuilder> 
        getAppleOrBuilderList();
    /**
     * <code>repeated .Apple apple = 2;</code>
     */
    com.danny.domain.proto.FruitProto.AppleOrBuilder getAppleOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Fruit}
   */
  public  static final class Fruit extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Fruit)
      FruitOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Fruit.newBuilder() to construct.
    private Fruit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Fruit() {
      category_ = "";
      apple_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Fruit(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              category_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                apple_ = new java.util.ArrayList<com.danny.domain.proto.FruitProto.Apple>();
                mutable_bitField0_ |= 0x00000002;
              }
              apple_.add(
                  input.readMessage(com.danny.domain.proto.FruitProto.Apple.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          apple_ = java.util.Collections.unmodifiableList(apple_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.danny.domain.proto.FruitProto.internal_static_Fruit_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.danny.domain.proto.FruitProto.internal_static_Fruit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.danny.domain.proto.FruitProto.Fruit.class, com.danny.domain.proto.FruitProto.Fruit.Builder.class);
    }

    private int bitField0_;
    public static final int CATEGORY_FIELD_NUMBER = 1;
    private volatile java.lang.Object category_;
    /**
     * <code>required string category = 1;</code>
     */
    public boolean hasCategory() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string category = 1;</code>
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          category_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string category = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPLE_FIELD_NUMBER = 2;
    private java.util.List<com.danny.domain.proto.FruitProto.Apple> apple_;
    /**
     * <code>repeated .Apple apple = 2;</code>
     */
    public java.util.List<com.danny.domain.proto.FruitProto.Apple> getAppleList() {
      return apple_;
    }
    /**
     * <code>repeated .Apple apple = 2;</code>
     */
    public java.util.List<? extends com.danny.domain.proto.FruitProto.AppleOrBuilder> 
        getAppleOrBuilderList() {
      return apple_;
    }
    /**
     * <code>repeated .Apple apple = 2;</code>
     */
    public int getAppleCount() {
      return apple_.size();
    }
    /**
     * <code>repeated .Apple apple = 2;</code>
     */
    public com.danny.domain.proto.FruitProto.Apple getApple(int index) {
      return apple_.get(index);
    }
    /**
     * <code>repeated .Apple apple = 2;</code>
     */
    public com.danny.domain.proto.FruitProto.AppleOrBuilder getAppleOrBuilder(
        int index) {
      return apple_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCategory()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAppleCount(); i++) {
        if (!getApple(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, category_);
      }
      for (int i = 0; i < apple_.size(); i++) {
        output.writeMessage(2, apple_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, category_);
      }
      for (int i = 0; i < apple_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, apple_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.danny.domain.proto.FruitProto.Fruit)) {
        return super.equals(obj);
      }
      com.danny.domain.proto.FruitProto.Fruit other = (com.danny.domain.proto.FruitProto.Fruit) obj;

      boolean result = true;
      result = result && (hasCategory() == other.hasCategory());
      if (hasCategory()) {
        result = result && getCategory()
            .equals(other.getCategory());
      }
      result = result && getAppleList()
          .equals(other.getAppleList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @SuppressWarnings("unchecked")
	@java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCategory()) {
        hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
        hash = (53 * hash) + getCategory().hashCode();
      }
      if (getAppleCount() > 0) {
        hash = (37 * hash) + APPLE_FIELD_NUMBER;
        hash = (53 * hash) + getAppleList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.danny.domain.proto.FruitProto.Fruit parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.danny.domain.proto.FruitProto.Fruit parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.danny.domain.proto.FruitProto.Fruit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.danny.domain.proto.FruitProto.Fruit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.danny.domain.proto.FruitProto.Fruit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.danny.domain.proto.FruitProto.Fruit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.danny.domain.proto.FruitProto.Fruit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.danny.domain.proto.FruitProto.Fruit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.danny.domain.proto.FruitProto.Fruit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.danny.domain.proto.FruitProto.Fruit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.danny.domain.proto.FruitProto.Fruit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.danny.domain.proto.FruitProto.Fruit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.danny.domain.proto.FruitProto.Fruit prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Fruit}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Fruit)
        com.danny.domain.proto.FruitProto.FruitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.danny.domain.proto.FruitProto.internal_static_Fruit_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.danny.domain.proto.FruitProto.internal_static_Fruit_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.danny.domain.proto.FruitProto.Fruit.class, com.danny.domain.proto.FruitProto.Fruit.Builder.class);
      }

      // Construct using com.danny.domain.proto.FruitProto.Fruit.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAppleFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        category_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (appleBuilder_ == null) {
          apple_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          appleBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.danny.domain.proto.FruitProto.internal_static_Fruit_descriptor;
      }

      public com.danny.domain.proto.FruitProto.Fruit getDefaultInstanceForType() {
        return com.danny.domain.proto.FruitProto.Fruit.getDefaultInstance();
      }

      public com.danny.domain.proto.FruitProto.Fruit build() {
        com.danny.domain.proto.FruitProto.Fruit result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.danny.domain.proto.FruitProto.Fruit buildPartial() {
        com.danny.domain.proto.FruitProto.Fruit result = new com.danny.domain.proto.FruitProto.Fruit(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.category_ = category_;
        if (appleBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            apple_ = java.util.Collections.unmodifiableList(apple_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.apple_ = apple_;
        } else {
          result.apple_ = appleBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.danny.domain.proto.FruitProto.Fruit) {
          return mergeFrom((com.danny.domain.proto.FruitProto.Fruit)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.danny.domain.proto.FruitProto.Fruit other) {
        if (other == com.danny.domain.proto.FruitProto.Fruit.getDefaultInstance()) return this;
        if (other.hasCategory()) {
          bitField0_ |= 0x00000001;
          category_ = other.category_;
          onChanged();
        }
        if (appleBuilder_ == null) {
          if (!other.apple_.isEmpty()) {
            if (apple_.isEmpty()) {
              apple_ = other.apple_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAppleIsMutable();
              apple_.addAll(other.apple_);
            }
            onChanged();
          }
        } else {
          if (!other.apple_.isEmpty()) {
            if (appleBuilder_.isEmpty()) {
              appleBuilder_.dispose();
              appleBuilder_ = null;
              apple_ = other.apple_;
              bitField0_ = (bitField0_ & ~0x00000002);
              appleBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAppleFieldBuilder() : null;
            } else {
              appleBuilder_.addAllMessages(other.apple_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCategory()) {
          return false;
        }
        for (int i = 0; i < getAppleCount(); i++) {
          if (!getApple(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.danny.domain.proto.FruitProto.Fruit parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.danny.domain.proto.FruitProto.Fruit) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object category_ = "";
      /**
       * <code>required string category = 1;</code>
       */
      public boolean hasCategory() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string category = 1;</code>
       */
      public java.lang.String getCategory() {
        java.lang.Object ref = category_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            category_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string category = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCategoryBytes() {
        java.lang.Object ref = category_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          category_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string category = 1;</code>
       */
      public Builder setCategory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string category = 1;</code>
       */
      public Builder clearCategory() {
        bitField0_ = (bitField0_ & ~0x00000001);
        category_ = getDefaultInstance().getCategory();
        onChanged();
        return this;
      }
      /**
       * <code>required string category = 1;</code>
       */
      public Builder setCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        category_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.danny.domain.proto.FruitProto.Apple> apple_ =
        java.util.Collections.emptyList();
      private void ensureAppleIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          apple_ = new java.util.ArrayList<com.danny.domain.proto.FruitProto.Apple>(apple_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.danny.domain.proto.FruitProto.Apple, com.danny.domain.proto.FruitProto.Apple.Builder, com.danny.domain.proto.FruitProto.AppleOrBuilder> appleBuilder_;

      /**
       * <code>repeated .Apple apple = 2;</code>
       */
      public java.util.List<com.danny.domain.proto.FruitProto.Apple> getAppleList() {
        if (appleBuilder_ == null) {
          return java.util.Collections.unmodifiableList(apple_);
        } else {
          return appleBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Apple apple = 2;</code>
       */
      public int getAppleCount() {
        if (appleBuilder_ == null) {
          return apple_.size();
        } else {
          return appleBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Apple apple = 2;</code>
       */
      public com.danny.domain.proto.FruitProto.Apple getApple(int index) {
        if (appleBuilder_ == null) {
          return apple_.get(index);
        } else {
          return appleBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Apple apple = 2;</code>
       */
      public Builder setApple(
          int index, com.danny.domain.proto.FruitProto.Apple value) {
        if (appleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppleIsMutable();
          apple_.set(index, value);
          onChanged();
        } else {
          appleBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Apple apple = 2;</code>
       */
      public Builder setApple(
          int index, com.danny.domain.proto.FruitProto.Apple.Builder builderForValue) {
        if (appleBuilder_ == null) {
          ensureAppleIsMutable();
          apple_.set(index, builderForValue.build());
          onChanged();
        } else {
          appleBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Apple apple = 2;</code>
       */
      public Builder addApple(com.danny.domain.proto.FruitProto.Apple value) {
        if (appleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppleIsMutable();
          apple_.add(value);
          onChanged();
        } else {
          appleBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Apple apple = 2;</code>
       */
      public Builder addApple(
          int index, com.danny.domain.proto.FruitProto.Apple value) {
        if (appleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppleIsMutable();
          apple_.add(index, value);
          onChanged();
        } else {
          appleBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Apple apple = 2;</code>
       */
      public Builder addApple(
          com.danny.domain.proto.FruitProto.Apple.Builder builderForValue) {
        if (appleBuilder_ == null) {
          ensureAppleIsMutable();
          apple_.add(builderForValue.build());
          onChanged();
        } else {
          appleBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Apple apple = 2;</code>
       */
      public Builder addApple(
          int index, com.danny.domain.proto.FruitProto.Apple.Builder builderForValue) {
        if (appleBuilder_ == null) {
          ensureAppleIsMutable();
          apple_.add(index, builderForValue.build());
          onChanged();
        } else {
          appleBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Apple apple = 2;</code>
       */
      public Builder addAllApple(
          java.lang.Iterable<? extends com.danny.domain.proto.FruitProto.Apple> values) {
        if (appleBuilder_ == null) {
          ensureAppleIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, apple_);
          onChanged();
        } else {
          appleBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Apple apple = 2;</code>
       */
      public Builder clearApple() {
        if (appleBuilder_ == null) {
          apple_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          appleBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Apple apple = 2;</code>
       */
      public Builder removeApple(int index) {
        if (appleBuilder_ == null) {
          ensureAppleIsMutable();
          apple_.remove(index);
          onChanged();
        } else {
          appleBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Apple apple = 2;</code>
       */
      public com.danny.domain.proto.FruitProto.Apple.Builder getAppleBuilder(
          int index) {
        return getAppleFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Apple apple = 2;</code>
       */
      public com.danny.domain.proto.FruitProto.AppleOrBuilder getAppleOrBuilder(
          int index) {
        if (appleBuilder_ == null) {
          return apple_.get(index);  } else {
          return appleBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Apple apple = 2;</code>
       */
      public java.util.List<? extends com.danny.domain.proto.FruitProto.AppleOrBuilder> 
           getAppleOrBuilderList() {
        if (appleBuilder_ != null) {
          return appleBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(apple_);
        }
      }
      /**
       * <code>repeated .Apple apple = 2;</code>
       */
      public com.danny.domain.proto.FruitProto.Apple.Builder addAppleBuilder() {
        return getAppleFieldBuilder().addBuilder(
            com.danny.domain.proto.FruitProto.Apple.getDefaultInstance());
      }
      /**
       * <code>repeated .Apple apple = 2;</code>
       */
      public com.danny.domain.proto.FruitProto.Apple.Builder addAppleBuilder(
          int index) {
        return getAppleFieldBuilder().addBuilder(
            index, com.danny.domain.proto.FruitProto.Apple.getDefaultInstance());
      }
      /**
       * <code>repeated .Apple apple = 2;</code>
       */
      public java.util.List<com.danny.domain.proto.FruitProto.Apple.Builder> 
           getAppleBuilderList() {
        return getAppleFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.danny.domain.proto.FruitProto.Apple, com.danny.domain.proto.FruitProto.Apple.Builder, com.danny.domain.proto.FruitProto.AppleOrBuilder> 
          getAppleFieldBuilder() {
        if (appleBuilder_ == null) {
          appleBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.danny.domain.proto.FruitProto.Apple, com.danny.domain.proto.FruitProto.Apple.Builder, com.danny.domain.proto.FruitProto.AppleOrBuilder>(
                  apple_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          apple_ = null;
        }
        return appleBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Fruit)
    }

    // @@protoc_insertion_point(class_scope:Fruit)
    private static final com.danny.domain.proto.FruitProto.Fruit DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.danny.domain.proto.FruitProto.Fruit();
    }

    public static com.danny.domain.proto.FruitProto.Fruit getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Fruit>
        PARSER = new com.google.protobuf.AbstractParser<Fruit>() {
      public Fruit parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Fruit(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Fruit> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Fruit> getParserForType() {
      return PARSER;
    }

    public com.danny.domain.proto.FruitProto.Fruit getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Apple)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required string color = 2;</code>
     */
    boolean hasColor();
    /**
     * <code>required string color = 2;</code>
     */
    java.lang.String getColor();
    /**
     * <code>required string color = 2;</code>
     */
    com.google.protobuf.ByteString
        getColorBytes();

    /**
     * <code>required int32 weight = 3;</code>
     */
    boolean hasWeight();
    /**
     * <code>required int32 weight = 3;</code>
     */
    int getWeight();
  }
  /**
   * Protobuf type {@code Apple}
   */
  public  static final class Apple extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Apple)
      AppleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Apple.newBuilder() to construct.
    private Apple(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Apple() {
      name_ = "";
      color_ = "";
      weight_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    @SuppressWarnings("unused")
	private Apple(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              color_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              weight_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.danny.domain.proto.FruitProto.internal_static_Apple_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.danny.domain.proto.FruitProto.internal_static_Apple_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.danny.domain.proto.FruitProto.Apple.class, com.danny.domain.proto.FruitProto.Apple.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLOR_FIELD_NUMBER = 2;
    private volatile java.lang.Object color_;
    /**
     * <code>required string color = 2;</code>
     */
    public boolean hasColor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string color = 2;</code>
     */
    public java.lang.String getColor() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          color_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string color = 2;</code>
     */
    public com.google.protobuf.ByteString
        getColorBytes() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        color_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEIGHT_FIELD_NUMBER = 3;
    private int weight_;
    /**
     * <code>required int32 weight = 3;</code>
     */
    public boolean hasWeight() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 weight = 3;</code>
     */
    public int getWeight() {
      return weight_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasColor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, color_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, weight_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, color_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, weight_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.danny.domain.proto.FruitProto.Apple)) {
        return super.equals(obj);
      }
      com.danny.domain.proto.FruitProto.Apple other = (com.danny.domain.proto.FruitProto.Apple) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasColor() == other.hasColor());
      if (hasColor()) {
        result = result && getColor()
            .equals(other.getColor());
      }
      result = result && (hasWeight() == other.hasWeight());
      if (hasWeight()) {
        result = result && (getWeight()
            == other.getWeight());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @SuppressWarnings("unchecked")
	@java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasColor()) {
        hash = (37 * hash) + COLOR_FIELD_NUMBER;
        hash = (53 * hash) + getColor().hashCode();
      }
      if (hasWeight()) {
        hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getWeight();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.danny.domain.proto.FruitProto.Apple parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.danny.domain.proto.FruitProto.Apple parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.danny.domain.proto.FruitProto.Apple parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.danny.domain.proto.FruitProto.Apple parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.danny.domain.proto.FruitProto.Apple parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.danny.domain.proto.FruitProto.Apple parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.danny.domain.proto.FruitProto.Apple parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.danny.domain.proto.FruitProto.Apple parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.danny.domain.proto.FruitProto.Apple parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.danny.domain.proto.FruitProto.Apple parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.danny.domain.proto.FruitProto.Apple parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.danny.domain.proto.FruitProto.Apple parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.danny.domain.proto.FruitProto.Apple prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Apple}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Apple)
        com.danny.domain.proto.FruitProto.AppleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.danny.domain.proto.FruitProto.internal_static_Apple_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.danny.domain.proto.FruitProto.internal_static_Apple_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.danny.domain.proto.FruitProto.Apple.class, com.danny.domain.proto.FruitProto.Apple.Builder.class);
      }

      // Construct using com.danny.domain.proto.FruitProto.Apple.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        color_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        weight_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.danny.domain.proto.FruitProto.internal_static_Apple_descriptor;
      }

      public com.danny.domain.proto.FruitProto.Apple getDefaultInstanceForType() {
        return com.danny.domain.proto.FruitProto.Apple.getDefaultInstance();
      }

      public com.danny.domain.proto.FruitProto.Apple build() {
        com.danny.domain.proto.FruitProto.Apple result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.danny.domain.proto.FruitProto.Apple buildPartial() {
        com.danny.domain.proto.FruitProto.Apple result = new com.danny.domain.proto.FruitProto.Apple(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.color_ = color_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.weight_ = weight_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.danny.domain.proto.FruitProto.Apple) {
          return mergeFrom((com.danny.domain.proto.FruitProto.Apple)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.danny.domain.proto.FruitProto.Apple other) {
        if (other == com.danny.domain.proto.FruitProto.Apple.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasColor()) {
          bitField0_ |= 0x00000002;
          color_ = other.color_;
          onChanged();
        }
        if (other.hasWeight()) {
          setWeight(other.getWeight());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasColor()) {
          return false;
        }
        if (!hasWeight()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.danny.domain.proto.FruitProto.Apple parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.danny.domain.proto.FruitProto.Apple) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object color_ = "";
      /**
       * <code>required string color = 2;</code>
       */
      public boolean hasColor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string color = 2;</code>
       */
      public java.lang.String getColor() {
        java.lang.Object ref = color_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            color_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string color = 2;</code>
       */
      public com.google.protobuf.ByteString
          getColorBytes() {
        java.lang.Object ref = color_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          color_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string color = 2;</code>
       */
      public Builder setColor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        color_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string color = 2;</code>
       */
      public Builder clearColor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        color_ = getDefaultInstance().getColor();
        onChanged();
        return this;
      }
      /**
       * <code>required string color = 2;</code>
       */
      public Builder setColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        color_ = value;
        onChanged();
        return this;
      }

      private int weight_ ;
      /**
       * <code>required int32 weight = 3;</code>
       */
      public boolean hasWeight() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 weight = 3;</code>
       */
      public int getWeight() {
        return weight_;
      }
      /**
       * <code>required int32 weight = 3;</code>
       */
      public Builder setWeight(int value) {
        bitField0_ |= 0x00000004;
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 weight = 3;</code>
       */
      public Builder clearWeight() {
        bitField0_ = (bitField0_ & ~0x00000004);
        weight_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Apple)
    }

    // @@protoc_insertion_point(class_scope:Apple)
    private static final com.danny.domain.proto.FruitProto.Apple DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.danny.domain.proto.FruitProto.Apple();
    }

    public static com.danny.domain.proto.FruitProto.Apple getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Apple>
        PARSER = new com.google.protobuf.AbstractParser<Apple>() {
      public Apple parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Apple(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Apple> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Apple> getParserForType() {
      return PARSER;
    }

    public com.danny.domain.proto.FruitProto.Apple getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Fruit_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Fruit_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Apple_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Apple_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014mobile.proto\"0\n\005Fruit\022\020\n\010category\030\001 \002(" +
      "\t\022\025\n\005apple\030\002 \003(\0132\006.Apple\"4\n\005Apple\022\014\n\004nam" +
      "e\030\001 \002(\t\022\r\n\005color\030\002 \002(\t\022\016\n\006weight\030\003 \002(\005B$" +
      "\n\026com.danny.domain.protoB\nFruitProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Fruit_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Fruit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Fruit_descriptor,
        new java.lang.String[] { "Category", "Apple", });
    internal_static_Apple_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Apple_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Apple_descriptor,
        new java.lang.String[] { "Name", "Color", "Weight", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
